"""initial revision

Revision ID: 51d6e03ecba
Revises: None
Create Date: 2015-06-04 21:58:29.508486

"""

# revision identifiers, used by Alembic.
revision = '51d6e03ecba'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_column('post', 'updated')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('job',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('params', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='job_pkey')
    )
    ### end Alembic commands ###
