"""initial revision

Revision ID: 51d6e03ecba
Revises: None
Create Date: 2015-06-04 21:58:29.508486

"""

# revision identifiers, used by Alembic.
revision = '51d6e03ecba'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
