"""add Attachment element

Revision ID: 93bd528a83
Revises: 51d6e03ecba
Create Date: 2015-06-04 22:02:36.082013

"""

# revision identifiers, used by Alembic.
revision = '93bd528a83'
down_revision = '51d6e03ecba'

from alembic import op
import sqlalchemy as sa


from redwind import create_app
from redwind import util
from redwind import admin
from redwind.models import Post, Attachment
from redwind.extensions import db
import os
import datetime
import random
import string
import mimetypes
import shutil
from flask import current_app


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'attachment',
        sa.Column('id', sa.Integer(), nullable=False, index=True),
        sa.Column('filename', sa.String(length=256), nullable=True),
        sa.Column('mimetype', sa.String(length=256), nullable=True),
        sa.Column('storage_path', sa.String(length=256), nullable=True),
        sa.Column('post_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
        sa.PrimaryKeyConstraint('id'))
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachment')
    # end Alembic commands ###

